#!/usr/bin/env node

var exec = require("child_process").exec
var watch = false
process.argv.forEach(function (val, index, array) {
  if (val === "--watch") watch = true
});

function bundle_python() {
  exec("python ./node_modules/pypyjs/tools/module_bundler.py add public/pypyjs/modules skulpt/src/builtin/pandas.py")
  exec("python ./node_modules/pypyjs/tools/module_bundler.py add public/pypyjs/modules skulpt/src/builtin/matplotlib")
}

bundle_python();

if (watch) setInterval(bundle_python,5000);
