#!/usr/bin/env node

var exec = require("child_process").exec
var watch = false
process.argv.forEach(function (val, index, array) {
  if (val === "--watch") watch = true
});

var fs = require("fs")

var files

function load_py(dir) {
  if (!fs.statSync(dir.join('/')).isDirectory()) return
  fs.readdirSync(dir.join('/')).forEach((file) => {
    var subdir = dir.concat([file])
    if (file.match(/\.(py|js)$/)) {
      files.push(subdir.slice(1).join('/'))
    } else {
      load_py(subdir)
    }
  })
}

function generate_pyload() {
  files = []
  load_py(["skulpt","src"])

  var body = [ "var Sk = require('./skulpt')","var f = []",""]
  files.forEach((file) => body.push('Sk.builtinFiles["files"]["' + file + '"] = require("!!raw!' + file  + '");'))
  body.push('')
  files.forEach((file) => body.push('f.push("' + file + '")'))
  body.push('')
  body.push('module.exports = { files: f }')
  fs.writeFileSync("src/pyload.js", body.join("\n"))
  exec("python ./node_modules/pypyjs/tools/module_bundler.py add public/pypyjs/modules skulpt/src/builtin/pandas.py")
  //console.log("imported skulpt files",files)
}

generate_pyload();

if (watch) setInterval(generate_pyload,5000);
