#!/bin/bash -x

npm install
go get github.com/lib/pq
go get github.com/mattn/go-sqlite3
go get github.com/jinzhu/gorm
go get github.com/gorilla/mux
go get github.com/gorilla/context
go get -u github.com/ddollar/forego

